name: project_two
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  package:
    path: ../package

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
